server:
  port: 8085
hm:
  db:
    database: hm-pay
  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
spring:
  rabbitmq:
    host: 192.168.150.101 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码

